# Generated by Django 4.0.6 on 2022-07-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="img",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="number",
            new_name="phone_number",
        ),
    ]
