# Generated by Django 4.0.6 on 2022-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="repeat",
        ),
        migrations.AddField(
            model_name="event",
            name="repeat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MON", "Каждый Понедельник"),
                    ("TUE", "Каждый Вторник"),
                    ("WED", "Каждую Среду"),
                    ("THU", "Каждый Четверг"),
                    ("FRI", "Каждую Пятницу"),
                    ("SAT", "Каждую Субботу"),
                    ("SUN", "Каждое Воскресенье"),
                    ("ED", "Каждый день"),
                    ("EWD", "Каждый будний день"),
                    ("EW", "Каждую неделю"),
                    ("EM", "Каждый месяц"),
                    ("EY", "Каждый год"),
                ],
                max_length=255,
                null=True,
                verbose_name="Цвета",
            ),
        ),
        migrations.DeleteModel(
            name="Repeat",
        ),
    ]
