# Generated by Django 4.0.6 on 2022-07-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="notification",
            new_name="notifications",
        ),
    ]
