# Generated by Django 4.0.6 on 2022-07-21 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageroom',
            old_name='id_room',
            new_name='room_image',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='user_event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_event_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='organization_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.organisation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type', to='app.eventtype'),
        ),
        migrations.AlterField(
            model_name='userparticipant',
            name='event_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participant', to='app.event'),
        ),
        migrations.AlterField(
            model_name='userparticipant',
            name='user_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
