# Generated by Django 4.0.5 on 2022-07-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpost",
            old_name="user_id",
            new_name="user",
        ),
    ]
