# Generated by Django 4.0.6 on 2022-07-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_id_room_imageroom_room_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='user_event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
