# Generated by Django 4.1.1 on 2022-09-29 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_eventtype_user_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
